// Single source of truth for visible copy across the site.
export const siteCopy = {
  global: {
    siteTitle: "Stories From Abroad",
    defaultDescription: "Essays, images, and fiction from somewhere else.",
    nav: {
      wordmark: "SFA",
      backLabel: "← Back",
      cta: "Subscribe",
      items: [
        { label: "About", path: "read-the-story" },
        { label: "Articles", path: "selected-papers" },
        { label: "Photography", path: "photography" },
        { label: "Faces", path: "faces-of-the-world" },
        { label: "Travel", path: "travel-stories" },
      ],
    },
    footer: {
      wordmark: "Stories From Abroad",
      homeLinks: [
        { label: "Home", path: "" },
        { label: "Selected Papers", path: "selected-papers" },
        { label: "Photography", path: "photography" },
      ],
      copyright: "\u00a9 2026 Stories From Abroad. All rights reserved.",
    },
    subscribeModal: {
      closeLabel: "Close",
      title: "Subscribe to Dispatches",
      subtitle: "No algorithms. No advertising. Just writing on the world we all inhabit.",
      emailLabel: "Email Address *",
      emailPlaceholder: "your@email.com",
      nameLabel: "Name (Optional)",
      namePlaceholder: "How should I address you?",
      preferenceLabel: "I am interested in",
      checkboxes: [
        "All updates",
        "Articles and Op-Eds",
        "Photography",
        "Faces of the World",
        "Travel",
      ],
      submitLabel: "Subscribe to the Letter",
      success: {
        title: "Welcome",
        subtitle: "Subscription received",
        body: "A confirmation email is on its way.",
      },
    },
  },
  home: {
    meta: {
      title: "Stories From Abroad",
      description: "Essays, photography, and field notes from every corner of the map I've been lucky enough to walk.",
    },
    hero: {
      eyebrowHtml: "Est. 2024 &middot; Dispatches from the World",
      titleMain: "Stories",
      titleEm: "From Abroad",
      subtitle: "Writing, photography, and reflection from the spaces between belonging.",
      mission:
        "Essays, images, and field notes gathered from the mundane to the extreme. A private letter, published.",
      ctaPrimary: "Read the Story",
      ctaSecondary: "Subscribe",
    },
    fourWays: {
      label: "What you will find here",
      title: "Four Ways of Observing",
      cards: [
        {
          title: "Articles & Op-Eds",
          text: "Long-form essays, cultural criticism, and analysis from a learner's perspective.",
          path: "selected-papers",
          iconHtml: "&#10022;",
        },
        {
          title: "Photography",
          text: "Visual stories, collections from the places words alone cannot quite reach.",
          path: "photography",
          iconHtml: "&#9675;",
        },
        {
          title: "Faces of the World",
          text: "Portraits and notes from ordinary people with extrodinary stories.",
          path: "faces-of-the-world",
          iconHtml: "&#9672;",
        },
        {
          title: "Travel",
          text: "Field dispatches, reflections, short stories from wherever life takes me.",
          path: "travel-stories",
          iconHtml: "&#9671;",
        },
      ],
    },
  },
  readStory: {
    meta: {
      title: "Read the Story",
      description: "The author and the project.",
    },
    header: {
      label: "About",
      title: "Read the Story",
      subtitle: "The author and the project behind Stories From Abroad.",
    },
    body: {
      title: "The Author and the Project",
      paragraphs: [
        "There is a particular clarity that comes from being away from home. From having traveled so much that the meaning home loses its significance. Living in places where the only recognizable thing is a human smile.",
        "Stories From Abroad is a personal dispatch, part literary journal, part field notebook, part brain dump. My simple attempt to record as much as possible, for story telling, regardless of its medium, brings life to living. I have not the skill of a journalist, nor the qualifications of an scholar. I have only eyes with which to observe.",
        "The photography is simply an attempt to capture a moment to be held forever. The essays are my raw thoughts. Each section has its own logic, but they share a common conviction: that the world is worth observing.",
        "Though I may find myself far from home, abroad in forign lands, adrift without anchor, I can know that there is, no matter where I land, a story worth telling.",
        "If you have found your way here, you are warmly invited to stay. Subscribe to receive dispatches when new work is published. No algorithms, no advertising. Just writing on the world we all inhabit.",
      ],
      portraitLabel: "Portrait Placeholder",
    },
    buttons: {
      primary: "Subscribe",
      secondary: "Read selected Papers",
    },
  },
  papers: {
    meta: {
      title: "Papers & Op-Eds - Stories From Abroad",
    },
    nav: {
      backLabel: "← Back",
      label: "Articles",
    },
    hero: {
      kicker: "Papers & Op-Eds",
      titleMain: "Selected",
      titleEm: "Writing",
      scrollHint: "...",
      byLabel: "By",
      byName: "Birkley Grunewald",
    },
    typewriterLines: [
      "Essays, notes, and arguments -- attempts to understand the world a little better.",
      "Some academic. Some opinionated. All written in good faith.",
      "Drafted with inspiration from travel across continents, rooted in the Duke academic foundation. Cultivated in China.",
      "An aspiting scholar's desk, left open.",
    ],
    featured: {
      label: "Featured Writing",
      button: "Read Paper ->",
      counterTemplate: "{current} of {total}",
      metaReadSuffix: " read",
    },
    defaults: {
      title: "Untitled",
      category: "Essay",
      time: "10 min",
      type: "Essay",
    },
    archive: {
      label: "The Archive",
      title: "All Writing",
      countPlaceholder: "Loading",
      countSingular: "paper",
      countPlural: "papers",
      searchPlaceholder: "Search by title, keyword, or topic...",
      filters: {
        categories: "All Categories",
        years: "All Years",
        type: "Writing Type",
      },
      emptyState: "No papers match your search.",
      readSuffix: " read",
    },
    author: {
      kicker: "About the Author",
      portraitLabel: "Portrait - Birkley Grunewald",
      name: "Birkley Grunewald",
      nameHtml: "Birkley<strong>Grunewald</strong>",
      role: "Student of Quantitative Political Economy at Duke Unviersity, China",
      bio: [
        "These papers represent an ongoing attempt to think clearly about politics, economy, and the structures that shape how people live. Inspired by travel and rooted in study, they range from formal academic arguments to shorter reflections on systemic and out of the box questions.",
        "The work sits alongside photography, travel writing, and the story of the people I meet along the way, each form asking a different kind of attention from the same underlying preoccupation.",
      ],
      tags: [
        "Political Economy",
        "State & Sovereignty",
        "Global Justice",
        "Development",
        "Corporate Governance",
        "International Order",
      ],
    },
    footer: {
      left: "Stories From Abroad - Papers & Op-Eds",
      right: "\u00a9 2026 Birkley Grunewald",
    },
    overlay: {
      backLabel: "Back to Papers",
      metaLabels: {
        author: "Author",
        date: "Date",
        readingTime: "Reading Time",
        keywords: "Keywords",
      },
      keywordsEmpty: "None",
      kwSeparator: " - ",
      timeSuffix: " read",
      citeLabel: "Cite This Paper",
      citeSource: "Stories From Abroad",
      citationAuthorShort: "Grunewald, B.",
      citationAuthorFull: "Grunewald, Birkley",
      citationAuthorBib: "Grunewald, Birkley",
      citationKey: "grunewald",
      citationStyles: ["APA", "MLA", "Chicago", "Harvard", "BibTeX"],
      abstractLabel: "Abstract",
      downloadButtons: ["Download PDF", "Clean Text", "Export Citation"],
      placeholder: {
        abstractParagraphs: [
          "The argument is situated within broader debates in comparative political economy and international relations, drawing on historical case studies and theoretical frameworks to illuminate patterns often obscured by narrowly empirical approaches.",
          "The paper ultimately suggests that structural conditions constrain but do not determine political possibilities, leaving open questions about agency, contingency, and the potential for deliberate institutional reform.",
        ],
        sectionMarks: ["I.", "II."],
        headings: ["The Problem of Governance", "Structure and Agency"],
        blockquote:
          "The strength of an institution lies not in its formal powers but in the expectations that surround it, in what people believe others believe about how it will behave.",
        bodyParagraphs: [
          "The question at the heart of this essay is neither new nor easily answered. It has occupied political economists, philosophers, and policymakers for decades, yet it returns with new urgency whenever institutions that were supposed to hold fail visibly, or when the gap between official explanation and lived experience becomes too wide to ignore.",
          "To understand what is at stake, we must first resist the temptation of abstraction. The forces under examination are not theoretical constructs but practical realities, they shape who gets what, when, and how. They determine whether hospitals receive funding, whether courts function with independence, whether citizens can trust the systems they live within.",
          "This is not merely an academic concern. The erosion of institutional trust has measurable consequences: for economic performance, for public health outcomes, for the willingness of citizens to participate in collective life.",
          "A second complication arises from the relationship between structure and agency. Structural arguments locate the causes of political outcomes in long-run economic forces, historical legacies, or international power configurations. They are indispensable but insufficient, explaining why certain paths are difficult without explaining why some actors navigate them successfully while others do not.",
          "The cases examined here suggest that agency matters most at critical junctures: moments when structural constraints are loosened by crisis, when existing arrangements have manifestly failed, and when political actors face genuine choices about institutional reform.",
        ],
      },
    },
    fallbackPapers: [
      {
        id: "p1",
        title: "On Belonging Nowhere in Particular",
        category: "Essay",
        year: 2025,
        date: "November 14, 2025",
        keywords: ["Identity", "Migration", "Home"],
        readTime: "12 min",
        type: "Essay",
        featured: true,
        summary:
          "A meditation on movement, memory, and the ways we build a sense of home without a fixed address.",
      },
      {
        id: "p2",
        title: "The Myth of the Authentic Experience",
        category: "Op-Ed",
        year: 2025,
        date: "October 3, 2025",
        keywords: ["Tourism", "Culture", "Power"],
        readTime: "8 min",
        type: "Op-Ed",
        featured: true,
        summary:
          "Tourism has always been a performance. The question is who performs for whom, and why.",
      },
      {
        id: "p3",
        title: "What the Markets Know That We Forgot",
        category: "Essay",
        year: 2025,
        date: "August 18, 2025",
        keywords: ["Political Economy", "Food", "Cities"],
        readTime: "15 min",
        type: "Essay",
        featured: false,
        summary:
          "From souks to street stalls, an inquiry into how markets reveal the structure of daily life.",
      },
      {
        id: "p4",
        title: "Against Technocracy",
        category: "Policy",
        year: 2024,
        date: "January 9, 2024",
        keywords: ["Democracy", "Governance"],
        readTime: "11 min",
        type: "Analysis",
        featured: true,
        summary:
          "A critique of administrative politics and what is lost when decisions detach from public life.",
      },
    ],
  },
  photography: {
    meta: {
      title: "Photography",
      description: "Stories From Abroad photography",
    },
    nav: {
      backLabel: "← Back",
      label: "Photography",
    },
    hero: {
      label: "Photography",
      titleLines: ["SEEN", "FELT", "KEPT"],
      subtitle: "Scroll to move through the work.",
      linkLabel: "View shoot ->",
    },
    archive: {
      label: "Archive",
      title: "All Shoots",
    },
    shootCountSuffix: "frames",
    footer: {
      left: "SFA",
      right: "Copyright 2026. All rights reserved.",
    },
    featured: [
      {
        src: "/photos/featured/tokyo-rain.jpg",
        demo: "https://picsum.photos/seed/bk_tok/1600/900",
        title: "Tokyo Rain",
        location: "Shibuya, Japan",
        shoot: "tokyo-fragments",
        accent: "#FF2D78",
      },
      {
        src: "/photos/featured/shanghai-bund.jpg",
        demo: "https://picsum.photos/seed/bk_shg/1600/900",
        title: "The Bund at Dusk",
        location: "Shanghai, China",
        shoot: "shanghai-nights",
        accent: "#1478FF",
      },
      {
        src: "/photos/featured/desert-bloom.jpg",
        demo: "https://picsum.photos/seed/bk_dsr/1600/900",
        title: "Desert Bloom",
        location: "Mojave, USA",
        shoot: "desert-bloom",
        accent: "#FF6500",
      },
      {
        src: "/photos/featured/pacific-dawn.jpg",
        demo: "https://picsum.photos/seed/bk_pac/1600/900",
        title: "Pacific Dawn",
        location: "Highway 1, California",
        shoot: "pacific-coast",
        accent: "#1478FF",
      },
      {
        src: "/photos/featured/studio-i.jpg",
        demo: "https://picsum.photos/seed/bk_std/1600/900",
        title: "Studio I",
        location: "New York, USA",
        shoot: "studio-series",
        accent: "#FF2D78",
      },
      {
        src: "/photos/featured/kyoto-winter.jpg",
        demo: "https://picsum.photos/seed/bk_kyt/1600/900",
        title: "Kyoto in Winter",
        location: "Kyoto, Japan",
        shoot: "kyoto-winter",
        accent: "#FF6500",
      },
    ],
    shoots: [
      {
        slug: "tokyo-fragments",
        title: "Tokyo Fragments",
        desc: "Quiet moments in a city that never stops moving.",
        date: "Nov 2024",
        loc: "Tokyo, Japan",
        tags: ["street", "night", "japan"],
        accent: "#FF2D78",
        cover: "https://picsum.photos/seed/tky/480/620",
        count: 12,
      },
      {
        slug: "shanghai-nights",
        title: "Shanghai After Dark",
        desc: "The city transforms when the lights come on.",
        date: "Sep 2024",
        loc: "Shanghai, China",
        tags: ["architecture", "neon"],
        accent: "#1478FF",
        cover: "https://picsum.photos/seed/shg/480/620",
        count: 10,
      },
      {
        slug: "desert-bloom",
        title: "Desert Bloom",
        desc: "Silence, scale, and impossible color.",
        date: "Mar 2024",
        loc: "Mojave, USA",
        tags: ["landscape", "golden hour"],
        accent: "#FF6500",
        cover: "https://picsum.photos/seed/dsr/480/620",
        count: 8,
      },
      {
        slug: "pacific-coast",
        title: "Pacific Coast",
        desc: "Highway 1, from the top to the bottom.",
        date: "Jul 2024",
        loc: "California, USA",
        tags: ["road trip", "ocean"],
        accent: "#1478FF",
        cover: "https://picsum.photos/seed/pac/480/620",
        count: 9,
      },
      {
        slug: "studio-series",
        title: "Studio Series I",
        desc: "Controlled light, unguarded moments.",
        date: "Jan 2025",
        loc: "New York, USA",
        tags: ["portrait", "studio", "fashion"],
        accent: "#FF2D78",
        cover: "https://picsum.photos/seed/std/480/620",
        count: 7,
      },
      {
        slug: "kyoto-winter",
        title: "Kyoto in Winter",
        desc: "Ancient temples under pale grey skies.",
        date: "Feb 2025",
        loc: "Kyoto, Japan",
        tags: ["travel", "temples"],
        accent: "#FF6500",
        cover: "https://picsum.photos/seed/kyt/480/620",
        count: 11,
      },
    ],
  },
  faces: {
    meta: {
      title: "Faces of the World",
      description: "Portraits and notes from people met along the way.",
    },
    navLabel: "Faces",
    nav: {
      backLabel: "← Back",
      logoMain: "Faces",
      logoEm: "of the World",
      searchPlaceholder: "Search portraits\u2026",
      archiveLabel: "Archive",
      aboutLabel: "About",
    },
    hero: {
      eyebrow: "A Documentary Portrait Archive",
      titleMain: "Faces",
      titleStrong: "of the World",
      subtitleHtml:
        "Portraits &amp; conversations from across the globe &mdash;<br>moments of work, faith, memory, and place.",
      scrollLabel: "Scroll to begin",
    },
    map: {
      loadingLabel: "Charting the world\u2026",
      unavailableLabel: "Map unavailable.",
    },
    archive: {
      searchPlaceholder: "Search name, place, occupation\u2026",
      faithLabel: "All faiths",
      faithOptions: [
        "Buddhist",
        "Catholic",
        "Christian",
        "Hindu",
        "Muslim",
        "Presbyterian",
        "Russian Orthodox",
      ],
      occupationLabel: "All occupations",
      occupationOptions: [
        "Beekeeper",
        "Carpenter",
        "Fisherman",
        "Handloom Weaver",
        "Ice Road Trucker",
        "Lighthouse Keeper, ret.",
        "Midwife",
        "Tea Farmer",
      ],
      yearLabel: "Any time",
      yearOptions: ["2026", "2025"],
      emptyState: "No portraits match.",
    },
    search: {
      headerAll: "All Portraits",
      headerMatches: "Portraits matching",
      emptyLabel: "No portraits found",
    },
    header: {
      label: "Portrait Series",
      title: "Faces of the World",
      subtitle: "Portraits and short notes from people met along the way.",
    },
    about: {
      eyebrow: "A Documentary Portrait Archive",
      titleMain: "Why these",
      titleStrong: "FACES",
      paragraphs: [
        "The most interesting people in the world are rarely the most famous. A carpenter in Accra who understands wood the way a poet understands language. A lighthouse keeper in Orkney who spent twenty-three years learning to be good company for herself. A tea farmer in Yunnan who tends trees older than anyone she has ever known.",
        "Faces of the World began with a simple conviction: that ordinary life, held up to the light, is never ordinary. Every person carries a body of knowledge built from decades of attention. That knowledge is rarely recorded. This project is an attempt to slow that erosion, one conversation at a time.",
        "Each entry is a single interview. The questions are the same across every subject: What do you do, and how did you learn to do it? What has your life taught you that you didn\u2019t expect? The answers, predictably, are never the same.",
        "This project began in Shanghai \u2014 in a semester spent studying abroad, looking out of windows, and noticing how vast and knowable the world truly is, just beyond them.",
      ],
      footer: "One interviewer. One recorder. No studio, no styling.",
    },
    cards: {
      portraitPrefix: "Portrait",
      previewButton: "Read their story \u2192",
      replacePhotoLabel: "Replace photo",
    },
    profile: {
      uploadPortraitLabel: "Click to upload portrait",
      addPhotoLabel: "Click to add photograph",
      backLabel: "All Portraits",
      labels: {
        age: "Age",
        faith: "Faith",
        work: "Work",
        location: "Location",
      },
    },
    fallbackFaces: [
      {
        id: "face-1",
        name: "Amina",
        location: "Casablanca, Morocco",
        year: "2025",
        note: "A portrait made in the last light, after a conversation about ferry rides and missed letters.",
        color: "linear-gradient(135deg,#2E2C28,#8B7040)",
      },
      {
        id: "face-2",
        name: "Jonas",
        location: "Oslo, Norway",
        year: "2024",
        note: "The kind of quiet that shows up in the eyes before it ever reaches the voice.",
        color: "linear-gradient(135deg,#2E3A44,#6E7F8A)",
      },
      {
        id: "face-3",
        name: "Linh",
        location: "Hanoi, Vietnam",
        year: "2025",
        note: "Hands ink-stained from a morning calligraphy lesson and a story about her grandmother.",
        color: "linear-gradient(135deg,#2F322A,#6B7C45)",
      },
      {
        id: "face-4",
        name: "Mateo",
        location: "Buenos Aires, Argentina",
        year: "2023",
        note: "A portrait from the corner cafe that keeps its lights on after the street goes dark.",
        color: "linear-gradient(135deg,#3A2C22,#7A5A3E)",
      },
    ],
    unknownName: "Unknown",
  },
  dispatches: {
    nav: {
      backLabel: "← Back",
      title: "The Scrap Sheet",
      links: ["Dispatches", "About", "Subscribe"],
      searchPlaceholder: "Search...",
      searchTooltip: "Search dispatches",
      searchResultsSuffix: "dispatches found",
    },
    hero: {
      lastReported: "Last reported from {location}",
      titleMain: "Scrap Notes",
      titleEm: "about the world.",
      subcopy: "Thoughts and discourse on the world for my international community.",
      countTemplate: "No. {current} of {total} dispatches filed",
      locationLabel: "\u2022 {location}",
    },
    currentLocation: {
      name: "Tbilisi, Georgia",
      lat: 41.69,
      lng: 44.83,
    },
    quotes: [
      { text: "Ferries here are not transport. They are philosophy.", postId: 4 },
      { text: "10 dirhams for five minutes of quiet.", postId: 2 },
      { text: "The evidence was destroyed immediately.", postId: 1 },
      { text: "It is impossibly, stubbornly itself.", postId: 1 },
      { text: "A person who needs food and sleep and occasionally to watch the sea.", postId: 3 },
      { text: "Nobody warned me \u2014 woodsmoke and roses.", postId: 1 },
      { text: "Whether it was silence, or just the permission to stop.", postId: 2 },
    ],
    filters: {
      label: "View",
      defaultCategoryLabel: "Dispatch",
      buttons: [
        { key: "all", label: "All" },
        { key: "travel", label: "Travel Dispatches" },
        { key: "stories", label: "Short Stories" },
        { key: "musings", label: "Musings" },
      ],
      emptyState: "No dispatches match your search.",
    },
    categories: {
      travel: { label: "Travel Update", color: "#1A5C40" },
      stories: { label: "Short Story", color: "#8B3A1A" },
      musings: { label: "Musing on the World", color: "#4A3272" },
    },
    posts: [
      {
        id: 1,
        category: "travel",
        location: "Tbilisi, Georgia",
        date: "2026-03-08",
        time: "11:42 PM",
        title: "The Wine is Free and the City Hums",
        preview:
          "Nobody warned me that Tbilisi would smell like woodsmoke and roses all at once. I arrived at midnight to find the old town still breathing \u2014 cafes spilling onto cobblestones, someone\u2019s grandmother leaning from a carved wooden balcony three floors up.",
        full:
          "Nobody warned me that Tbilisi would smell like woodsmoke and roses all at once. I arrived at midnight to find the old town still breathing \u2014 cafes spilling onto cobblestones, someone\u2019s grandmother leaning from a carved wooden balcony three floors up, a dog that seemed to own the street entirely.\n\nGeorgian wine is served like water here. Not with ceremony. Just poured. And the food \u2014 I have been eating khinkali every single day. I have been eating them wrong every single day. Nobody has stopped me.\n\nThe thing about Georgia nobody tells you: it is impossibly, stubbornly itself. Hundreds of years of being invaded and it still has its own alphabet, its own wine, its own polyphonic singing that makes you feel something in your chest you do not have a word for.\n\nI am staying in a guesthouse run by a woman named Nino who insists on feeding me breakfast even when I am trying to leave early. I am never trying that hard.",
        photos: [
          {
            url: "https://picsum.photos/seed/tbilisi1/1200/800",
            caption: "The old town from the cable car. Everything still lit at midnight.",
          },
          { url: "https://picsum.photos/seed/tbilisi2/1200/800", caption: "Khinkali, wrong end up. Still perfect." },
          {
            url: "https://picsum.photos/seed/tbilisi3/1200/800",
            caption: "Nino\u2019s guesthouse garden. 7am. Breakfast I did not ask for.",
          },
        ],
        defaultReactions: { "\u2764\uFE0F": 12, "\uD83D\uDD25": 8, "\u2708\uFE0F": 15 },
        pinned: true,
      },
      {
        id: 2,
        category: "stories",
        location: "Marrakech, Morocco",
        date: "2026-02-21",
        time: "3:17 PM",
        title: "The Man Who Sold Silence",
        preview:
          "He sat at the edge of the Djemaa el-Fna every evening with nothing in front of him. No snake, no spice, no carpet. Just a small sign: 10 dirhams for five minutes of quiet.",
        full:
          "He sat at the edge of the Djemaa el-Fna every evening with nothing in front of him. No snake, no spice, no carpet. Just a small sign that read: 10 dirhams for five minutes of quiet.\n\nI paid him on a Tuesday.\n\nHe gestured to the stool beside him, and I sat, and he folded his hands, and we watched the square together without speaking. The drums were still there. None of it went away. But he looked at it with such complete calm that the chaos became, briefly, something you could hold.\n\nAfter five minutes he raised a hand. That was it. I thanked him in broken Darija and he nodded once, like he already knew.\n\nI have thought about him a lot since then. What he was actually selling. Whether it was silence, or just the permission to stop.",
        photos: [
          {
            url: "https://picsum.photos/seed/marrakech1/1200/800",
            caption: "Djemaa el-Fna from above. The square that never empties.",
          },
          {
            url: "https://picsum.photos/seed/marrakech2/1200/800",
            caption: "His corner. The stool was still there the next day.",
          },
        ],
        defaultReactions: { "\u2764\uFE0F": 34, "\uD83D\uDE2E": 7, "\uD83D\uDD25": 19 },
        pinned: false,
      },
      {
        id: 3,
        category: "musings",
        location: "Somewhere over the Black Sea",
        date: "2026-02-14",
        time: "7:03 AM",
        title: "On Being a Stranger",
        preview:
          "There is a particular freedom in being somewhere no one has any expectations of you. You are just a shape moving through a city that has its own complete life without you.",
        full:
          "There is a particular freedom in being somewhere no one has any expectations of you. You are just a shape moving through a city that has its own complete life without you. It does not need you. The city is fine.\n\nAt home, I am a collection of things people know about me. Here I am just someone who ordered the wrong thing at dinner and laughed about it and walked home in the rain.\n\nI used to think travel was about seeing things. I think it is more about temporarily shedding the story you have built around yourself. Usually something simpler. Something more animal. A person who needs food and sleep and occasionally to watch the sea.\n\nWhat I keep wondering: why does it take this \u2014 thousands of miles and a language I cannot speak \u2014 to feel this uncomplicated?",
        photos: [],
        defaultReactions: { "\u2764\uFE0F": 28, "\uD83D\uDE2E": 4, "\uD83D\uDD25": 11 },
        pinned: false,
      },
      {
        id: 4,
        category: "travel",
        location: "Istanbul, Turkey",
        date: "2026-01-30",
        time: "6:22 PM",
        title: "Straddling Two Continents for a Simit",
        preview:
          "I walked across the Galata Bridge just to buy a simit from the Asian side. This is the kind of decision that travel turns you into \u2014 a person who makes small unnecessary pilgrimages because the geography feels meaningful.",
        full:
          "I walked across the Galata Bridge just to buy a simit from the Asian side. This is the kind of decision that travel turns you into: a person who makes small unnecessary pilgrimages because the geography of it feels meaningful.\n\nIstanbul is overwhelming in the best possible way. It is a city that has absorbed empires and spat them out and kept the good parts of each. Byzantine mosaics under Ottoman domes. Greek ruins next to Roman aqueducts.\n\nI drank cay in a tea garden overlooking the Bosphorus and watched the tankers go past. Enormous, lumbering, completely out of place next to the little fishing boats. That image felt like the whole city somehow.\n\nFerries here are not transport. They are philosophy.",
        photos: [
          {
            url: "https://picsum.photos/seed/istanbul1/1200/800",
            caption: "The Bosphorus from Beyo\u011flu. Two continents, one horizon.",
          },
          {
            url: "https://picsum.photos/seed/istanbul2/1200/800",
            caption: "Galata Bridge at 6am. Fishermen before the commuters.",
          },
          {
            url: "https://picsum.photos/seed/istanbul3/1200/800",
            caption: "A simit. The entire reason I crossed continents.",
          },
        ],
        defaultReactions: {
          "\u2764\uFE0F": 19,
          "\uD83D\uDE02": 6,
          "\u2708\uFE0F": 22,
          "\uD83D\uDD25": 13,
        },
        pinned: false,
      },
    ],
    defaultComments: {
      1: [
        {
          id: 1,
          text: "The grandmother on the balcony \u2014 I can picture it exactly",
          author: "Maya K.",
          time: "11:58 PM",
          isAuthor: false,
        },
        {
          id: 2,
          text: "How are you eating khinkali wrong?? I need photographic evidence",
          author: "Tom R.",
          time: "12:03 AM",
          isAuthor: false,
        },
        {
          id: 3,
          text: "No evidence exists. The evidence was destroyed immediately.",
          author: "The Correspondent",
          time: "12:05 AM",
          isAuthor: true,
        },
      ],
      2: [
        { id: 1, text: "I read this three times. That last line.", author: "Priya S.", time: "4:02 PM", isAuthor: false },
        { id: 2, text: "Did you get his name?", author: "James W.", time: "4:45 PM", isAuthor: false },
        { id: 3, text: "I didn\u2019t. I think that was part of it.", author: "The Correspondent", time: "5:01 PM", isAuthor: true },
      ],
      3: [],
      4: [
        {
          id: 1,
          text: "Ferries here are not transport. They are philosophy. \u2014 printing this out.",
          author: "Sophia L.",
          time: "7:30 PM",
          isAuthor: false,
        },
      ],
    },
    postModal: {
      minReadSuffix: "min read",
      reactLabel: "React",
      repliesLabel: "Replies \u00b7 {count}",
      emptyReplies: "No replies yet -- start the thread.",
      namePlaceholder: "Your name (optional)",
      commentPlaceholder: "Add to the thread...",
      sendLabel: "Send",
      defaultAuthor: "Anonymous",
    },
    emojiSections: [
      { label: "Quick", emojis: ["\u2764\uFE0F", "\uD83D\uDD25", "\uD83D\uDE02", "\uD83D\uDE2E", "\u2708\uFE0F", "\uD83C\uDF0D", "\uD83D\uDC4F", "\u2728", "\uD83E\uDD73", "\uD83D\uDCAF"] },
      { label: "Hearts", emojis: ["\uD83E\uDDE1", "\uD83D\uDC9B", "\uD83D\uDC9A", "\uD83D\uDC99", "\uD83D\uDC9C", "\uD83E\uDD0D", "\uD83D\uDC94", "\u2763\uFE0F", "\uD83E\uFAF6", "\uD83D\uDC95", "\uD83D\uDC96", "\uD83D\uDC9D", "\uD83D\uDC9E"] },
      { label: "Faces", emojis: ["\uD83D\uDE00", "\uD83D\uDE02", "\uD83E\uDD72", "\uD83D\uDE0D", "\uD83E\uDD29", "\uD83D\uDE0E", "\uD83E\uDD7A", "\uD83D\uDE2D", "\uD83D\uDE24", "\uD83E\uDD14", "\uD83E\uDD2F", "\uD83D\uDE43", "\uD83D\uDE0C", "\uD83D\uDE05", "\uD83E\uDD23", "\uD83D\uDE22", "\uD83E\uDD70", "\uD83D\uDE1A"] },
      { label: "Travel", emojis: ["\u2708\uFE0F", "\uD83C\uDF0D", "\uD83C\uDF0E", "\uD83C\uDF0F", "\uD83D\uDDFA\uFE0F", "\uD83E\uDDED", "\uD83C\uDFD4\uFE0F", "\uD83C\uDF05", "\uD83C\uDF0A", "\uD83E\uDDF3", "\uD83D\uDCF8", "\uD83C\uDFDB\uFE0F", "\uD83D\uDE82", "\uD83D\uDEA2", "\u26FA", "\uD83C\uDFD5\uFE0F", "\uD83C\uDFDD\uFE0F", "\uD83D\uDD4C"] },
      { label: "Vibes", emojis: ["\uD83D\uDD25", "\u2728", "\u2B50", "\uD83D\uDCAB", "\uD83C\uDF1F", "\uD83C\uDF89", "\uD83D\uDC4F", "\uD83D\uDE4C", "\uD83D\uDC4D", "\uD83E\uDEF6", "\uD83D\uDC40", "\uD83D\uDCAC", "\uD83D\uDCAD", "\uD83C\uDFC6"] },
      { label: "Life", emojis: ["\u2615", "\uD83C\uDF77", "\uD83E\uDD42", "\uD83C\uDF3F", "\uD83C\uDF38", "\uD83C\uDF19", "\uD83C\uDF1E", "\uD83C\uDF08", "\uD83D\uDCDD", "\u270F\uFE0F", "\uD83D\uDCD6", "\uD83D\uDCCC", "\uD83D\uDD16", "\uD83D\uDCDA", "\u2712\uFE0F", "\uD83D\uDDDE\uFE0F", "\u2709\uFE0F"] },
    ],
    about: {
      label: "About This Page",
      titleMain: "Why I Keep Sending",
      titleEm: "You These",
      paragraphs: [
        "I had a WhatsApp group with over 50 people who wanted to keep track of me while I traveled abroad. They would react with emojis and inside jokes and the occasional message asking if I was alive at 2am (mostly from my mom). No matter where in the world I was, I had my community around me.",
        "This is the same thing, but slower. More considered. A little more permanent. I write these for the same reason I wrote those WhatsApp updates -- because something is lost when we experience things without trying to articulate them, and the world gets smaller when you only talk to people who already see it the way you do.",
        "Agree with me. Argue with me. Tell me what you are reading. Leave a comment. Suggest a place. The whole point is that you are here.",
      ],
      signatureName: "The Correspondent",
      signatureLine: "Writing from abroad, always.",
      signatureInitials: "BTG",
    },
    footer: {
      title: "The Scrap Sheet",
      subtitle: "Written from the road. Read anywhere.",
      subscribeLabel: "Subscribe ->",
    },
    postCard: {
      openLabel: "Open dispatch ->",
      photoSingular: "photo",
      photoPlural: "photos",
    },
    subscribeModal: {
      label: "New Dispatches",
      title: "Stay in the thread.",
      body:
        "Add your email and I will send a note when something new lands here. No schedule. Just when it is ready.",
      emailPlaceholder: "your@email.com",
      button: "Subscribe",
      successTitle: "You are in.",
      successBody: "Next dispatch will find you. Until then.",
    },
    pinnedLabel: "PINNED",
  },
} as const;
